"""empty message

Revision ID: 0edf64a31311
Revises: a4d39b99cac6
Create Date: 2017-08-10 12:52:49.808557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0edf64a31311'
down_revision = 'a4d39b99cac6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories_items',
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], )
    )
    op.drop_table('items_categories')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items_categories',
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='items_categories_category_id_fkey'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name='items_categories_item_id_fkey')
    )
    op.drop_table('categories_items')
    # ### end Alembic commands ###
